### ISSUE TITLE
Bubbles not moving anymore?

### ISSUE THREAD

**Issue by pm990320** [BeXcellent/Bexcellent-2#34]
Just noticed this on my way in,  was this an intentional change to the design? The bubbles on gateway page and top of every other page don't seem to move anymore. I'm looking into it now...

**Comment by Melvin106** [comment]
Noticed that too.

**Comment by OscarOrSomething** [comment]
Just looked into this, It seems that the $ function isn't detected even though jQuery is being included.

**Comment by OscarOrSomething** [comment]
No idea why. I'll check if there's a way to upgrade the jquery version, that could be it.

**Comment by OscarOrSomething** [comment]
Ok, Fixed this by installing a plugin to upgrade wordpress' jquery. Can someone else confirm it's working?
