### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by pm990320** [BeXcellent/Bexcellent-2#35]
Is someone working on/updating the server? Tired to access webpage and getting error

**Comment by OscarOrSomething** [comment]
Back up. Can't see why it crashed. The server does need some maintenance though.

**Comment by pm990320** [comment]
Anything in the logs?  Yes there was a new version of ubuntu to install if I remember rightly, as well as lots of updates

**Comment by OscarOrSomething** [comment]
I'm updating everythin now, I think it ran out of memory.

**Comment by markmacgillivray** [comment]
Hi guys, is the site back up then? Just had a msg from Lesley so I'll need
to update her.

**Comment by OscarOrSomething** [comment]
I've done the update but apache is being weird.

**Comment by OscarOrSomething** [comment]
Everything is back up now but the server needs a restart. Does that need to be done through the control panel?

**Comment by markmacgillivray** [comment]
sudo reboot should do it
