### ISSUE TITLE
*.bexcellent.org.uk -> Server

### ISSUE THREAD

**Issue by OscarOrSomething** [BeXcellent/Bexcellent-2#36]
@markmacgillivray Can you forward all subdomains to the server, @Steven-Eardley Only has access to bexcellent.cottagelabs.com

**Comment by markmacgillivray** [comment]
Hello Oscar, unfortunately not. The bexcellent.org.uk domain name is owned and controlled by Children in Scotland. You would have to ask Linda to ask their IT admins to forward all subdomains to the same IP that the main address is forwarded to. Which they should be able to do very easily.

**Comment by OscarOrSomething** [comment]
Ok. Thanks.
