### ISSUE TITLE
Catlist styling - missing icons & layout

### ISSUE THREAD

**Issue by pm990320** [BeXcellent/Bexcellent-2#37]
http://bexcellent.org.uk/articles/

Perhaps change to bootstrap Thumbnails ?

**Comment by pm990320** [comment]
Added in bootstrap thumbnails - already looking slightly better

**Comment by pm990320** [comment]
Sorted this layout, perhaps more padding/minor improvements etc?

**Comment by OscarOrSomething** [comment]
I think it's fine as is. Square images for all posts would be good though.

**Comment by pm990320** [comment]
Well, in any case I've now added rounded borders to the boxes and thumbnails and more padding so it looks a bit better - and a default image if there is no post thumbnail too.

**Comment by OscarOrSomething** [comment]
Cool.
