### ISSUE TITLE
Photo gallery... Missing???

### ISSUE THREAD

**Issue by pm990320** [BeXcellent/Bexcellent-2#40]
Photo gallery seems to be gone...

"Our gallery is not currently available."

Investigate, and get back up and running

**Comment by pm990320** [comment]
Got it... now just need to add the images in again as they seem to have disappeared...again

**Comment by OscarOrSomething** [comment]
Is this done? Let me know if you need any help

**Comment by pm990320** [comment]
This is one of these menial tasks I despise... I'll see what I can do today & I'll see if there's a better plugin for the gallery too

**Comment by OscarOrSomething** [comment]
I'll do it, Pretty sure it's my fault it broke in the first place.

**Comment by OscarOrSomething** [comment]
Using new gallery plugin, Added images which aren't post images, etc.

There's not much, I assume we have some from the conference we can add. Will search hard drive.

**Comment by pm990320** [comment]
Ah you're too kind, I would have done it haha   Yep, I'm pretty sure there's more, even from the photo shoot day too

**Comment by OscarOrSomething** [comment]
Got some on my hard drive. Will take a look right now and caption them soon.

**Comment by OscarOrSomething** [comment]
Added everything I have to the [Gallery](http://bexcellent.org.uk/gallery/photos/), Feel free to add/remove stuff.
