### ISSUE TITLE
General styling

### ISSUE THREAD

**Issue by pm990320** [BeXcellent/Bexcellent-2#41]
- New font?
- Increased padding for main body of text
- Menu responsive hiding, like bootstrap rather than wrapping onto a new line
- Improved link colour/behaviour

**Comment by Melvin106** [comment]
Comic Sans

**Comment by Melvin106** [comment]
I'm sorry don't even read that.

**Comment by OscarOrSomething** [comment]
Roboto?

**Comment by pm990320** [comment]
Roboto sounds like a good bet - updated everything to Roboto in style.css

**Comment by pm990320** [comment]
It was already imported as well so we must have used it at some point ?

**Comment by OscarOrSomething** [comment]
Can't remember when but I do remember using it.

**Comment by pm990320** [comment]
Done all these things today at action day
