### ISSUE TITLE
Background Enhancements

### ISSUE THREAD

**Issue by tcmal** [BeXcellent/Bexcellent-2#44]
The background cuts off after a certain point: http://i.imgur.com/tMCqGE0.png

Also, Is there any way to stop the slow loading animation where it sweeps from top to bottom - Preloading maybe?

We could also use something from [Subtle Patterns](http://subtlepatterns.com/) rather than super big (outdated) photos.

Will fix the cutoff right now, Let me know what you think of the other stuff.

**Comment by pm990320** [comment]
Could implement the background image switching differently, and make a pre loading script.

Also, making the existing backgrounds lower res ? 

The only thing about those patterns is they aren't really relevant to education/children - but I agree that we do need to update them with something else

**Comment by OscarOrSomething** [comment]
Yep. Will discuss updating images at next meeting
