### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by OscarOrSomething** [BeXcellent/Bexcellent-2#46]
Not sure where the server is hosted but it seems to be down right now?

**Comment by pm990320** [comment]
Got an email from DigitalOcean about maintenance on the 17th of May but not heard anything else. Pretty sure this is hosted by CottageLabs, should probably let Lynn or Roslynn know.

**Comment by markmacgillivray** [comment]
Hi! Yes CL still host the machine on our DO account. It does appear to be inaccessible, and yes there is maintenance happening at DO today in the region this machine is in, although it was not expected to cause long outages. The DO graphs show CPU has been at 100% for days though, but with low bandwidth, which could indicate a problem with configuration of something on the machine. I am going to force a restart now, and see what happens.

**Comment by markmacgillivray** [comment]
Reboot has sorted it. I see that discourse is running on that machine, and presumably still wordpress too? That is a lot of load, and WP is notoriously unstable, and I have seen numerous other projects find their machines unstable when running this combination (and sometimes even just one of them at a time). The CPU usage is back down now, and RAM too - I'd recommend you keep an eye on them, they may ramp up again and get stuck at max, and eventually the machine would become inaccessible again.

**Comment by OscarOrSomething** [comment]
Thanks. In that case, It might be best to disable discourse for now and see if we can put it on another server? Just a thought.
